update error comment; address review comments about workflow

diff --git a/.github/workflows/cam_sima_fortran_ci.yml b/.github/workflows/cam_sima_fortran_ci.yml
--- a/.github/workflows/cam_sima_fortran_ci.yml
+++ b/.github/workflows/cam_sima_fortran_ci.yml
@@ -229,7 +229,7 @@ jobs:
 
       - name: Lint Fortran source code
         run: |
-          set -o pipefail
+          set -euo pipefail
 
           # Retrieve the matched paths.
           echo "${{ needs.conditional-check.outputs.matched-paths }}" | base64 -d > matched-paths.txt
@@ -247,12 +247,10 @@ jobs:
               source venv-fortitude/bin/activate
 
               # Convert the errors file into a comma-separated list.
-              # Blank lines and comments are ignored
+              # Blank lines and comments are ignored.
               ERROR_CODES="$(
-                sed 's/[[:space:]]*#.*$//' \
+                sed -Ene 's/^[[:blank:]]*([[:alnum:]]+)[[:blank:]]*(#.*)?$/\1/p' \
                   "$SOURCE_CODE_PATH/test/fortitude-errors.txt" |
-                sed 's/^[[:space:]]*//;s/[[:space:]]*$//' |
-                sed '/^$/d' |
                 paste -sd, - || true
               )"
 
@@ -261,21 +259,21 @@ jobs:
               echo "=== Fortitude errors ===" | tee -a "$SOURCE_CODE_PATH/source-code-linting.log"
 
               # First run: report rules that are meant to fail the job if they are triggered.
-              # This pass determines the exit status of the lint job
+              # This pass determines the exit status of the lint job.
+              LINT_STATUS=0
               fortitude \
                 --config-file "$SOURCE_CODE_PATH/test/fortitude.toml" \
                 check \
                 --select "$ERROR_CODES" \
                 --output-format github \
                 "$@" |
-                tee -a "$SOURCE_CODE_PATH/source-code-linting.log" |
-                sed -e "s|file=$SOURCE_CODE_PATH/|file=|g"
-              LINT_STATUS=${PIPESTATUS[0]}
+                  tee -a "$SOURCE_CODE_PATH/source-code-linting.log" |
+                  sed -e "s|file=$SOURCE_CODE_PATH/|file=|g" || LINT_STATUS="${PIPESTATUS[0]}"
 
               echo "" | tee -a "$SOURCE_CODE_PATH/source-code-linting.log"
               echo "=== Fortitude warnings ===" | tee -a "$SOURCE_CODE_PATH/source-code-linting.log"
 
-              # Second run: report warning-only rules, but don't fail the job
+              # Second run: report warning-only rules, but don't fail the job.
               fortitude \
                 --config-file "$SOURCE_CODE_PATH/test/fortitude.toml" \
                 check \
